### ISSUE TITLE
CapsLock键的功能异常

### ISSUE THREAD

**Issue by HencyChine** [lotem/rime-gits#21]
之前使用Weasel的时候对CapsLK的定义是：

```
ascii_composer:
  good_old_caps_lock: true
  switch_key: 
    Caps_Lock: clear
```

这样在中文输入状态下第一次按CapsLK，会切换到西文模式并大写，再次按下会切换回中文模式并小写。而在rime-gits中CapsLK只能实现从中文到西文的切换，之后就只能改变大小写而无法再切换回中文模式。

更严重的问题是当把Caps_Lock设为noop的时候，按下CapsLK之后会进入异常的输入状态，输入的大写字母会停留在屏幕上，既不能用空格上屏也无法删除，按下回车则会上屏两次。再次按下CapsLK可恢复正常的中文模式。
